version: 0.2

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  pre_build:
    commands:
      - dotnet restore ./API/SeiyuuMoe.sln
  build:
    commands:
      - dotnet build -c Release ./API/SeiyuuMoe.sln
      - dotnet test -c Release ./API/SeiyuuMoe.Tests.Unit/SeiyuuMoe.Tests.Application.csproj
      - dotnet test -c Release ./API/SeiyuuMoe.Tests.Component/SeiyuuMoe.Tests.Component.csproj
      - dotnet test -c Release ./API/Tests/SeiyuuMoe.Tests.Domain/SeiyuuMoe.Tests.Domain.csproj
      - dotnet test -c Release ./API/Tests/SeiyuuMoe.Tests.Infrastructure.Database/SeiyuuMoe.Tests.Infrastructure.Database.csproj
      - dotnet test -c Release ./API/SeiyuuMoe.Tests.E2E/SeiyuuMoe.Tests.E2E.csproj