CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Season" (
"Id" INTEGER NOT NULL CONSTRAINT "PK_Season" PRIMARY KEY AUTOINCREMENT,
"Year" INTEGER NOT NULL,
"Name" TEXT NULL);
CREATE TABLE IF NOT EXISTS "AnimeStatus" (
"Id" INTEGER NOT NULL CONSTRAINT "PK_AnimeStatus" PRIMARY KEY AUTOINCREMENT,
"Name" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "AnimeType" (
"Id" INTEGER NOT NULL CONSTRAINT "PK_AnimeType" PRIMARY KEY AUTOINCREMENT,
"Name" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "Language" (
"Id" INTEGER NOT NULL CONSTRAINT "PK_Language" PRIMARY KEY AUTOINCREMENT,
"Name" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "RoleType" (
"Id" INTEGER NOT NULL CONSTRAINT "PK_RoleType" PRIMARY KEY AUTOINCREMENT,
"Name" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "BlacklistedId" (
"Id" INTEGER NOT NULL CONSTRAINT "PK_BlacklistedId" PRIMARY KEY AUTOINCREMENT,
"MalId" INTEGER NOT NULL,
"EntityType" TEXT NOT NULL,
"Reason" TEXT NULL);
CREATE TABLE IF NOT EXISTS "Role" (
"Id" INTEGER NOT NULL CONSTRAINT "PK_Role" PRIMARY KEY AUTOINCREMENT,
"AnimeId" INTEGER NULL,
"RoleTypeId" INTEGER NULL,
"CharacterId" INTEGER NULL,
"SeiyuuId" INTEGER NULL,
"LanguageId" INTEGER NULL,
FOREIGN KEY(AnimeId) REFERENCES Anime(MalId) ON DELETE CASCADE,
FOREIGN KEY(RoleTypeId) REFERENCES RoleType(Id) ON DELETE CASCADE,
FOREIGN KEY(CharacterId) REFERENCES Character(MalId) ON DELETE CASCADE,
FOREIGN KEY(SeiyuuId) REFERENCES Seiyuu(MalId) ON DELETE CASCADE,
FOREIGN KEY(LanguageId) REFERENCES Language(Id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS "Anime" (
"MalId" INTEGER NOT NULL CONSTRAINT "PK_Anime" PRIMARY KEY,
"Title" TEXT NOT NULL,
"ImageUrl" TEXT NULL,
"Popularity" INTEGER NULL,
"JapaneseTitle" TEXT NULL,
"TitleSynonyms" TEXT NULL,
"About" TEXT NULL,
"AiringDate" NUMERIC NULL,
"StatusId" INTEGER NULL,
"TypeId" INTEGER NULL,
"SeasonId" INTEGER NULL, EnglishTitle TEXT NULL,
FOREIGN KEY(StatusId) REFERENCES AnimeStatus(Id) ON DELETE SET NULL,
FOREIGN KEY(TypeId) REFERENCES AnimeType(Id) ON DELETE SET NULL,
FOREIGN KEY(SeasonId) REFERENCES Season(Id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS "Seiyuu" (
"MalId" INTEGER NOT NULL CONSTRAINT "PK_Seiyuu" PRIMARY KEY,
"Name" TEXT NOT NULL,
"ImageUrl" TEXT NULL,
"Popularity" INTEGER NULL,
"JapaneseName" TEXT NULL,
"About" TEXT NULL,
"Birthday" NUMERIC NULL);
CREATE TABLE IF NOT EXISTS "Character" (
"MalId" INTEGER NOT NULL CONSTRAINT "PK_Character" PRIMARY KEY,
"Name" TEXT NOT NULL,
"ImageUrl" TEXT NULL,
"Popularity" INTEGER NULL,
"NameKanji" TEXT NULL,
"About" TEXT NULL,
"Nicknames" TEXT NULL);
